/**
 * The command tour — driven by the CLI's own clap tree.
 *
 * ─── ⚠️ Why there is no list of commands in this file ────────────────────────
 *
 * There have been five documentation errors of one shape in this project, and
 * every one was found by a hand sweep, which does not repeat:
 *
 *   • `evnx vault rekey` documented before it existed
 *   • `commands/auth` missing four subcommands for a whole release
 *   • `cloud delete-version` shipping with no row in its own table
 *   • `EVNX_COMMANDS` in evnx-web omitting `spec` entirely
 *   • PyPI shipping five releases with no cloud commands at all
 *
 * All of them are "a second list of what the CLI does, maintained by hand".
 * `command-surface.json` is generated by `evnx surface`, which walks the same
 * clap tree that parses the arguments — so a new command appears in this tour
 * by construction, and a removed one cannot linger.
 *
 * ⚠️ **NOTES ARE AN OVERLAY, NEVER THE SPINE.** The prose below is keyed by
 * command path. A command with no note still appears, described by its own
 * `--help` text. A note for a command that no longer exists is reported by
 * {@link tourDrift} rather than silently rendering nothing — because an orphaned
 * note is the same failure in miniature, and it is the one that would creep back.
 */

import surface from "@/data/command-surface.json";

/** Bumped by `evnx surface` when the payload shape changes. */
const SUPPORTED_SCHEMA = 1;

export type SurfaceArg = {
  id: string;
  long: string | null;
  short: string | null;
  help: string | null;
  value_name: string | null;
  required: boolean;
  takes_value: boolean;
  positional: boolean;
  multiple: boolean;
  hidden: boolean;
};

export type SurfaceCommand = {
  path: string[];
  name: string;
  about: string | null;
  visible_aliases: string[];
  aliases: string[];
  hidden: boolean;
  docs_url: string | null;
  args: SurfaceArg[];
};

export type Surface = {
  schema: number;
  evnx_version: string;
  features: string[];
  commands: SurfaceCommand[];
};

const data = surface as Surface;

/** The CLI version this tour describes. Shown, because it will go stale. */
export const EVNX_VERSION = data.evnx_version;

/**
 * ⚠️ Top-level commands that need an account.
 *
 * The one hand-kept list here, and it is four strings rather than eighty — the
 * difference that matters. `clap` does not know which Cargo feature gated a
 * command (an absent command is simply absent), so this cannot be derived from
 * the surface.
 *
 * It degrades safely: a fifth cloud command that nobody adds here appears under
 * "On your machine" — visible and mis-grouped, never missing. {@link tourDrift}
 * reports any entry that no longer exists.
 */
const CLOUD_ROOTS = ["auth", "vault", "org", "cloud"] as const;

/**
 * An order for the first few, so the tour opens on something useful rather than
 * alphabetically on `add`.
 *
 * ⚠️ A ranking, not a list. Anything unranked sorts after, in surface order, so
 * forgetting to rank a new command costs it a position and never its place.
 */
const FIRST: readonly string[] = ["init", "scan", "validate", "diff", "convert"];

export type TourGroup = {
  id: "local" | "cloud";
  title: string;
  blurb: string;
  commands: TourCommand[];
};

export type TourCommand = SurfaceCommand & {
  /** Hand-written, optional. See the note at the top of this file. */
  note?: string;
  /** A copy-pasteable line. Optional, same rule. */
  example?: string;
  subcommands: SurfaceCommand[];
};

/**
 * Prose, keyed by top-level command.
 *
 * ⚠️ Every key must exist in the surface — {@link tourDrift} is what enforces
 * it. Nothing here decides *which* commands the tour shows.
 */
const NOTES: Record<string, { note: string; example?: string }> = {
  init: {
    note: "Start here. Walks your project, works out what it needs, and writes a .env.example other people can actually use.",
    example: "evnx init",
  },
  scan: {
    note: "Finds credentials that look real — AWS keys, tokens, connection strings — including ones pasted inside a multiline value. Exit 1 means it found something.",
    example: "evnx scan --severity high",
  },
  validate: {
    note: "Checks your .env against .env.example: what is missing, what is extra, what is the wrong shape.",
    example: "evnx validate",
  },
  diff: {
    note: "Shows what differs between two environments. ⚠️ It exits 1 on a healthy project too — branch on the summary counts, never the exit code.",
    example: "evnx diff .env .env.production",
  },
  convert: {
    note: "Turns a .env into any of fourteen deployment formats — Docker, Kubernetes, Terraform, GitHub Actions and more.",
    example: "evnx convert --to docker-compose",
  },
  add: { note: "Adds variables to an existing .env, with presets for common services and frameworks." },
  spec: { note: "Declare what each variable is — required, its format, whether it is secret — so validate can enforce it." },
  sync: { note: "Keeps .env and .env.example in step, so a new variable never reaches someone else's machine undocumented." },
  template: { note: "Generates config files from templates, filling them from your .env." },
  doctor: { note: "Checks your .env files, Git config and project structure for the mistakes that leak secrets." },
  migrate: {
    note: "Moves secrets into a hosted secret manager. ⚠️ Eight of the nine destinations print the commands for you to run; only GitHub Actions uploads directly.",
  },
  backup: { note: "An encrypted backup of a .env, under a password you choose." },
  restore: { note: "Restores one of those backups." },
  update: { note: "Tells you how to upgrade, by the channel you installed from." },
  completions: { note: "Shell completions for bash, zsh, fish and PowerShell." },

  auth: {
    note: "Your account: register, sign in, second factor, API tokens for CI, and the devices you have signed in from.",
    example: "evnx auth login",
  },
  vault: {
    note: "A vault holds one .env, versioned. Sharing wraps the key for the other person — the server cannot do it for you, which is the point.",
    example: "evnx vault share app/production --with colleague@example.com",
  },
  cloud: {
    note: "Push encrypts on your machine and uploads ciphertext; pull downloads and decrypts. `run` injects secrets into a command without writing a file at all.",
    example: "evnx cloud run --vault app/production -- ./deploy.sh",
  },
  org: {
    note: "An organisation owns a plan and a set of seats. ⛔ It does not give anyone access to a vault — that is always `evnx vault share`.",
    example: "evnx org billing",
  },
};

function isCloud(root: string): boolean {
  return (CLOUD_ROOTS as readonly string[]).includes(root);
}

/** Top-level, visible commands, ranked. */
function roots(): SurfaceCommand[] {
  const top = data.commands.filter((c) => c.path.length === 1 && !c.hidden);
  return top.sort((a, b) => {
    const ia = FIRST.indexOf(a.name);
    const ib = FIRST.indexOf(b.name);
    if (ia !== -1 || ib !== -1) {
      return (ia === -1 ? Number.MAX_SAFE_INTEGER : ia) - (ib === -1 ? Number.MAX_SAFE_INTEGER : ib);
    }
    return 0; // surface order, which is clap's declaration order
  });
}

export function tourGroups(): TourGroup[] {
  const build = (ids: SurfaceCommand[]): TourCommand[] =>
    ids.map((c) => ({
      ...c,
      note: NOTES[c.name]?.note,
      example: NOTES[c.name]?.example,
      // ⚠️ Every descendant, not just depth 2. The first version filtered on
      // `path.length === 2` and silently dropped eleven commands —
      // `auth token create`, `auth totp enable`, `auth sessions revoke` and the
      // rest. A tour that is missing commands is the exact failure the generated
      // spine exists to prevent, reintroduced by the consumer.
      // `unreachableCommands()` is the check that now catches it.
      subcommands: data.commands.filter(
        (s) => s.path.length > 1 && s.path[0] === c.name && !s.hidden,
      ),
    }));

  const all = roots();
  return [
    {
      id: "local",
      title: "On your machine",
      blurb:
        "No account, no network. These work on a plane, in an air-gapped build, and in a CI job with egress rules.",
      commands: build(all.filter((c) => !isCloud(c.name))),
    },
    {
      id: "cloud",
      title: "With an evnx account",
      blurb:
        "Encrypted sync, team sharing and plans. Everything is encrypted on your machine before it leaves — the server holds only ciphertext it cannot read.",
      commands: build(all.filter((c) => isCloud(c.name))),
    },
  ];
}

/**
 * Everything the tour can tell is wrong about itself.
 *
 * ⚠️ This is the point of the whole design. The generated spine cannot drift,
 * but the overlay can — so the overlay is checked against the spine and the
 * result is **rendered**, not logged. A warning nobody sees is not a check.
 */
export function tourDrift(): string[] {
  const problems: string[] = [];

  if (data.schema !== SUPPORTED_SCHEMA) {
    problems.push(
      `command-surface.json is schema ${data.schema}; this tour understands ${SUPPORTED_SCHEMA}. Regenerate it and update src/lib/tour.ts together.`,
    );
  }

  if (!data.features.includes("cloud")) {
    problems.push(
      "command-surface.json came from a binary built without the `cloud` feature, so every cloud command is missing from this tour.",
    );
  }

  // ⚠️ The check that matters: does the tour actually reach every command?
  //
  // A generated list is only half the guarantee — the consumer can still drop
  // part of it. This one did, on the first attempt, by assuming subcommands
  // were one level deep.
  const unreachable = unreachableCommands();
  if (unreachable.length > 0) {
    problems.push(
      `${unreachable.length} command${unreachable.length === 1 ? " is" : "s are"} in the CLI but not shown anywhere in this tour: ${unreachable
        .slice(0, 6)
        .join(", ")}${unreachable.length > 6 ? ", …" : ""}`,
    );
  }

  const names = new Set(data.commands.filter((c) => c.path.length === 1).map((c) => c.name));

  for (const key of Object.keys(NOTES)) {
    if (!names.has(key)) {
      problems.push(`a tour note describes \`evnx ${key}\`, which is no longer a command.`);
    }
  }
  for (const root of CLOUD_ROOTS) {
    if (!names.has(root)) {
      problems.push(`\`${root}\` is listed as a cloud command but is not in the surface.`);
    }
  }
  for (const r of FIRST) {
    if (!names.has(r)) {
      problems.push(`\`${r}\` is ranked first in the tour but is not a command.`);
    }
  }

  return problems;
}

/**
 * Visible commands in the surface that the tour does not render.
 *
 * ⚠️ Compares against what {@link tourGroups} actually builds, not against what
 * it is supposed to build — a check written from the same assumption as the code
 * it checks would have passed while eleven commands were missing.
 */
export function unreachableCommands(): string[] {
  const shown = new Set<string>();
  for (const g of tourGroups()) {
    for (const c of g.commands) {
      shown.add(c.path.join(" "));
      for (const s of c.subcommands) shown.add(s.path.join(" "));
    }
  }
  return data.commands
    .filter((c) => !c.hidden)
    .map((c) => c.path.join(" "))
    .filter((p) => !shown.has(p));
}

/** `evnx vault share` — for display and copying. */
export function invocation(c: { path: string[] }): string {
  return `evnx ${c.path.join(" ")}`;
}

/** `--severity <LEVEL>`, or `--verbose` for a flag. */
export function flagLabel(a: SurfaceArg): string {
  if (a.positional) return `<${a.value_name ?? a.id.toUpperCase()}>`;
  const name = a.long ? `--${a.long}` : a.short ? `-${a.short}` : a.id;
  return a.takes_value ? `${name} <${a.value_name ?? "VALUE"}>` : name;
}
