/**
 * A guided tour of every evnx command.
 *
 * ⛔ **Nothing here enumerates commands.** The list comes from
 * `command-surface.json`, generated by `evnx surface` from clap's own tree. See
 * `lib/tour.ts` for why that matters and what it is protecting against.
 *
 * ⚠️ `tourDrift()` is rendered, not logged. A check whose output goes to the
 * console is a check nobody runs.
 */

"use client";

import { useMemo, useState } from "react";
import {
  EVNX_VERSION,
  flagLabel,
  invocation,
  tourDrift,
  tourGroups,
  type TourCommand,
} from "@/lib/tour";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

export function CommandTour() {
  const groups = useMemo(() => tourGroups(), []);
  const drift = useMemo(() => tourDrift(), []);
  const [query, setQuery] = useState("");

  const q = query.trim().toLowerCase();
  const filtered = useMemo(
    () =>
      groups
        .map((g) => ({
          ...g,
          commands: g.commands.filter((c) => {
            if (!q) return true;
            // Match the parent, its blurb, or any subcommand — so searching
            // "share" finds `vault`, which is where `share` lives.
            return (
              c.name.includes(q) ||
              (c.about ?? "").toLowerCase().includes(q) ||
              (c.note ?? "").toLowerCase().includes(q) ||
              c.subcommands.some((s) => s.path.join(" ").includes(q))
            );
          }),
        }))
        .filter((g) => g.commands.length > 0),
    [groups, q],
  );

  const total = groups.reduce(
    (n, g) => n + g.commands.length + g.commands.reduce((m, c) => m + c.subcommands.length, 0),
    0,
  );

  return (
    <div className="space-y-6">
      {/* ⚠️ Rendered. See the module note. */}
      {drift.length > 0 && (
        <Alert variant="destructive">
          <AlertTitle>This tour has drifted from the CLI</AlertTitle>
          <AlertDescription>
            <ul className="list-disc space-y-1 pl-4">
              {drift.map((d) => (
                <li key={d}>{d}</li>
              ))}
            </ul>
          </AlertDescription>
        </Alert>
      )}

      <div className="flex flex-wrap items-center justify-between gap-3">
        <p className="text-sm text-muted-foreground">
          {total} commands, read from evnx{" "}
          <span className="font-mono">{EVNX_VERSION}</span> itself.
        </p>
        <Input
          value={query}
          onChange={(e) => setQuery(e.target.value)}
          placeholder="Search commands…"
          aria-label="Search commands"
          className="w-full max-w-xs"
        />
      </div>

      {filtered.length === 0 && (
        <p className="text-sm text-muted-foreground">
          Nothing matches <span className="font-mono">{query}</span>.
        </p>
      )}

      {filtered.map((g) => (
        <section key={g.id} className="space-y-3">
          <div>
            <h2 className="font-heading text-base font-medium">{g.title}</h2>
            <p className="mt-1 max-w-[72ch] text-sm text-muted-foreground">{g.blurb}</p>
          </div>
          <div className="space-y-2">
            {g.commands.map((c) => (
              <CommandCard key={c.name} command={c} expandAll={q.length > 0} />
            ))}
          </div>
        </section>
      ))}
    </div>
  );
}

function CommandCard({
  command,
  expandAll,
}: {
  command: TourCommand;
  expandAll: boolean;
}) {
  const hasDetail = command.subcommands.length > 0 || command.args.length > 0;

  return (
    /* ⚠️ `<details>`, not React state — it is keyboard- and screen-reader
       navigable for free, survives a re-render, and needs no effect to tear
       down. The same reasoning as the mobile nav in app-shell. */
    <details
      open={expandAll}
      className="group rounded-lg border border-[var(--border-subtle)] transition-colors open:border-[var(--border-muted)]"
    >
      <summary
        className={
          "flex cursor-pointer list-none items-start gap-3 p-3 " +
          (hasDetail ? "" : "cursor-default")
        }
      >
        <code className="shrink-0 rounded bg-[var(--bg-overlay)] px-1.5 py-0.5 font-mono text-sm text-primary">
          {invocation(command)}
        </code>
        <span className="min-w-0 flex-1 text-sm text-muted-foreground">
          {command.note ?? command.about ?? "—"}
        </span>
        {hasDetail && (
          <span
            aria-hidden="true"
            className="shrink-0 text-muted-foreground transition-transform group-open:rotate-90"
          >
            ›
          </span>
        )}
      </summary>

      <div className="space-y-4 border-t border-[var(--border-subtle)] p-3">
        {/* The one-liner from the binary, when a hand-written note replaced it
            above. Keeping both means the authoritative text is never hidden. */}
        {command.note && command.about && (
          <p className="text-xs text-muted-foreground">
            <span className="font-mono">--help</span>: {command.about}
          </p>
        )}

        {command.example && <Example line={command.example} />}

        {command.subcommands.length > 0 && (
          <div className="space-y-1.5">
            <p className="text-xs text-muted-foreground">
              {command.subcommands.length} subcommand
              {command.subcommands.length === 1 ? "" : "s"}
            </p>
            <ul className="space-y-1">
              {command.subcommands.map((s) => (
                <li key={s.path.join(" ")} className="flex flex-wrap items-baseline gap-2">
                  <code className="font-mono text-sm">{invocation(s)}</code>
                  <span className="text-xs text-muted-foreground">{s.about ?? ""}</span>
                </li>
              ))}
            </ul>
          </div>
        )}

        {command.args.length > 0 && (
          <div className="space-y-1.5">
            <p className="text-xs text-muted-foreground">Options</p>
            <ul className="flex flex-wrap gap-1.5">
              {command.args
                .filter((a) => !a.hidden)
                .map((a) => (
                  <li
                    key={a.id}
                    title={a.help ?? undefined}
                    className="rounded border border-[var(--border-subtle)] px-1.5 py-0.5 font-mono text-xs text-muted-foreground"
                  >
                    {flagLabel(a)}
                  </li>
                ))}
            </ul>
          </div>
        )}

        {/* ⚠️ The URL comes from the binary's own `docs.rs`, not composed from
            the command name — so it is the same link `--help` prints. A
            command with no guide yet shows no link rather than a 404. */}
        {command.docs_url && (
          <a
            className="inline-block text-sm underline"
            href={command.docs_url}
            target="_blank"
            rel="noopener noreferrer"
          >
            Full guide ↗
          </a>
        )}
      </div>
    </details>
  );
}

function Example({ line }: { line: string }) {
  const [copied, setCopied] = useState(false);
  return (
    <div className="flex items-center gap-2 rounded-md border border-[var(--border-subtle)] bg-[var(--terminal-bg,var(--bg-overlay))] px-2.5 py-2">
      <span aria-hidden="true" className="font-mono text-sm text-primary">
        $
      </span>
      <code className="min-w-0 flex-1 overflow-x-auto font-mono text-sm">{line}</code>
      <Button
        size="xs"
        variant="ghost"
        onClick={() => {
          // ⚠️ Wrapped: the Clipboard API throws in an insecure context and
          // when permission is refused, and an unhandled rejection here would
          // take the page's error boundary with it over a copy button.
          navigator.clipboard?.writeText(line).then(
            () => {
              setCopied(true);
              setTimeout(() => setCopied(false), 1500);
            },
            () => setCopied(false),
          );
        }}
      >
        {copied ? "copied" : "copy"}
      </Button>
    </div>
  );
}
